package kurs

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

func GetKurs() *autoGenerated {

	get := "https://www.cbr-xml-daily.ru/daily_json.js"

	resp, err := http.Get(get)
	if err != nil {
		log.Fatalln(err)
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}

	var s autoGenerated

	if err := json.Unmarshal(body, &s); err != nil {
		fmt.Println(err)

	}

	return &s
}
